#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuongmaiDienTu.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ThuongMaiDienTu")]
	public partial class TMDTDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTinTuc(TinTuc instance);
    partial void UpdateTinTuc(TinTuc instance);
    partial void DeleteTinTuc(TinTuc instance);
    partial void InsertThongBao(ThongBao instance);
    partial void UpdateThongBao(ThongBao instance);
    partial void DeleteThongBao(ThongBao instance);
    partial void InsertSuKien(SuKien instance);
    partial void UpdateSuKien(SuKien instance);
    partial void DeleteSuKien(SuKien instance);
    partial void InsertNhomHocPhan(NhomHocPhan instance);
    partial void UpdateNhomHocPhan(NhomHocPhan instance);
    partial void DeleteNhomHocPhan(NhomHocPhan instance);
    partial void InsertNguoiDung(NguoiDung instance);
    partial void UpdateNguoiDung(NguoiDung instance);
    partial void DeleteNguoiDung(NguoiDung instance);
    partial void InsertNamHoc(NamHoc instance);
    partial void UpdateNamHoc(NamHoc instance);
    partial void DeleteNamHoc(NamHoc instance);
    partial void InsertLienHe(LienHe instance);
    partial void UpdateLienHe(LienHe instance);
    partial void DeleteLienHe(LienHe instance);
    partial void InsertKieuNguoiDung(KieuNguoiDung instance);
    partial void UpdateKieuNguoiDung(KieuNguoiDung instance);
    partial void DeleteKieuNguoiDung(KieuNguoiDung instance);
    partial void InsertHocPhan(HocPhan instance);
    partial void UpdateHocPhan(HocPhan instance);
    partial void DeleteHocPhan(HocPhan instance);
    partial void InsertGiangVien(GiangVien instance);
    partial void UpdateGiangVien(GiangVien instance);
    partial void DeleteGiangVien(GiangVien instance);
    partial void InsertDangNhap(DangNhap instance);
    partial void UpdateDangNhap(DangNhap instance);
    partial void DeleteDangNhap(DangNhap instance);
    partial void InsertDanhMucTinTuc(DanhMucTinTuc instance);
    partial void UpdateDanhMucTinTuc(DanhMucTinTuc instance);
    partial void DeleteDanhMucTinTuc(DanhMucTinTuc instance);
    partial void InsertCongTacGiangDay(CongTacGiangDay instance);
    partial void UpdateCongTacGiangDay(CongTacGiangDay instance);
    partial void DeleteCongTacGiangDay(CongTacGiangDay instance);
    partial void InsertBoMon(BoMon instance);
    partial void UpdateBoMon(BoMon instance);
    partial void DeleteBoMon(BoMon instance);
    #endregion
		
		public TMDTDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ThuongMaiDienTuConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TMDTDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TMDTDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TMDTDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TMDTDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TinTuc> TinTucs
		{
			get
			{
				return this.GetTable<TinTuc>();
			}
		}
		
		public System.Data.Linq.Table<ThongBao> ThongBaos
		{
			get
			{
				return this.GetTable<ThongBao>();
			}
		}
		
		public System.Data.Linq.Table<SuKien> SuKiens
		{
			get
			{
				return this.GetTable<SuKien>();
			}
		}
		
		public System.Data.Linq.Table<NhomHocPhan> NhomHocPhans
		{
			get
			{
				return this.GetTable<NhomHocPhan>();
			}
		}
		
		public System.Data.Linq.Table<NguoiDung> NguoiDungs
		{
			get
			{
				return this.GetTable<NguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<NamHoc> NamHocs
		{
			get
			{
				return this.GetTable<NamHoc>();
			}
		}
		
		public System.Data.Linq.Table<LienHe> LienHes
		{
			get
			{
				return this.GetTable<LienHe>();
			}
		}
		
		public System.Data.Linq.Table<KieuNguoiDung> KieuNguoiDungs
		{
			get
			{
				return this.GetTable<KieuNguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<HocPhan> HocPhans
		{
			get
			{
				return this.GetTable<HocPhan>();
			}
		}
		
		public System.Data.Linq.Table<GiangVien> GiangViens
		{
			get
			{
				return this.GetTable<GiangVien>();
			}
		}
		
		public System.Data.Linq.Table<DangNhap> DangNhaps
		{
			get
			{
				return this.GetTable<DangNhap>();
			}
		}
		
		public System.Data.Linq.Table<DanhMucTinTuc> DanhMucTinTucs
		{
			get
			{
				return this.GetTable<DanhMucTinTuc>();
			}
		}
		
		public System.Data.Linq.Table<CongTacGiangDay> CongTacGiangDays
		{
			get
			{
				return this.GetTable<CongTacGiangDay>();
			}
		}
		
		public System.Data.Linq.Table<BoMon> BoMons
		{
			get
			{
				return this.GetTable<BoMon>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TinTuc")]
	public partial class TinTuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDTinTuc;
		
		private System.Nullable<int> _IDDanhMucTinTuc;
		
		private string _TieuDeTinTuc;
		
		private System.Data.Linq.Binary _HinhAnhTinTuc;
		
		private string _NoiDungTinTuc;
		
		private System.Nullable<System.DateTime> _NgayDangTinTuc;
		
		private string _NguoiDangTin;
		
		private EntityRef<DanhMucTinTuc> _DanhMucTinTuc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDTinTucChanging(int value);
    partial void OnIDTinTucChanged();
    partial void OnIDDanhMucTinTucChanging(System.Nullable<int> value);
    partial void OnIDDanhMucTinTucChanged();
    partial void OnTieuDeTinTucChanging(string value);
    partial void OnTieuDeTinTucChanged();
    partial void OnHinhAnhTinTucChanging(System.Data.Linq.Binary value);
    partial void OnHinhAnhTinTucChanged();
    partial void OnNoiDungTinTucChanging(string value);
    partial void OnNoiDungTinTucChanged();
    partial void OnNgayDangTinTucChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDangTinTucChanged();
    partial void OnNguoiDangTinChanging(string value);
    partial void OnNguoiDangTinChanged();
    #endregion
		
		public TinTuc()
		{
			this._DanhMucTinTuc = default(EntityRef<DanhMucTinTuc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTinTuc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDTinTuc
		{
			get
			{
				return this._IDTinTuc;
			}
			set
			{
				if ((this._IDTinTuc != value))
				{
					this.OnIDTinTucChanging(value);
					this.SendPropertyChanging();
					this._IDTinTuc = value;
					this.SendPropertyChanged("IDTinTuc");
					this.OnIDTinTucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDanhMucTinTuc", DbType="Int")]
		public System.Nullable<int> IDDanhMucTinTuc
		{
			get
			{
				return this._IDDanhMucTinTuc;
			}
			set
			{
				if ((this._IDDanhMucTinTuc != value))
				{
					if (this._DanhMucTinTuc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDDanhMucTinTucChanging(value);
					this.SendPropertyChanging();
					this._IDDanhMucTinTuc = value;
					this.SendPropertyChanged("IDDanhMucTinTuc");
					this.OnIDDanhMucTinTucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDeTinTuc", DbType="NVarChar(MAX)")]
		public string TieuDeTinTuc
		{
			get
			{
				return this._TieuDeTinTuc;
			}
			set
			{
				if ((this._TieuDeTinTuc != value))
				{
					this.OnTieuDeTinTucChanging(value);
					this.SendPropertyChanging();
					this._TieuDeTinTuc = value;
					this.SendPropertyChanged("TieuDeTinTuc");
					this.OnTieuDeTinTucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnhTinTuc", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary HinhAnhTinTuc
		{
			get
			{
				return this._HinhAnhTinTuc;
			}
			set
			{
				if ((this._HinhAnhTinTuc != value))
				{
					this.OnHinhAnhTinTucChanging(value);
					this.SendPropertyChanging();
					this._HinhAnhTinTuc = value;
					this.SendPropertyChanged("HinhAnhTinTuc");
					this.OnHinhAnhTinTucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungTinTuc", DbType="NVarChar(MAX)")]
		public string NoiDungTinTuc
		{
			get
			{
				return this._NoiDungTinTuc;
			}
			set
			{
				if ((this._NoiDungTinTuc != value))
				{
					this.OnNoiDungTinTucChanging(value);
					this.SendPropertyChanging();
					this._NoiDungTinTuc = value;
					this.SendPropertyChanged("NoiDungTinTuc");
					this.OnNoiDungTinTucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDangTinTuc", DbType="Date")]
		public System.Nullable<System.DateTime> NgayDangTinTuc
		{
			get
			{
				return this._NgayDangTinTuc;
			}
			set
			{
				if ((this._NgayDangTinTuc != value))
				{
					this.OnNgayDangTinTucChanging(value);
					this.SendPropertyChanging();
					this._NgayDangTinTuc = value;
					this.SendPropertyChanged("NgayDangTinTuc");
					this.OnNgayDangTinTucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiDangTin", DbType="NVarChar(50)")]
		public string NguoiDangTin
		{
			get
			{
				return this._NguoiDangTin;
			}
			set
			{
				if ((this._NguoiDangTin != value))
				{
					this.OnNguoiDangTinChanging(value);
					this.SendPropertyChanging();
					this._NguoiDangTin = value;
					this.SendPropertyChanged("NguoiDangTin");
					this.OnNguoiDangTinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DanhMucTinTuc_TinTuc", Storage="_DanhMucTinTuc", ThisKey="IDDanhMucTinTuc", OtherKey="IDDanhMucTinTuc", IsForeignKey=true)]
		public DanhMucTinTuc DanhMucTinTuc
		{
			get
			{
				return this._DanhMucTinTuc.Entity;
			}
			set
			{
				DanhMucTinTuc previousValue = this._DanhMucTinTuc.Entity;
				if (((previousValue != value) 
							|| (this._DanhMucTinTuc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DanhMucTinTuc.Entity = null;
						previousValue.TinTucs.Remove(this);
					}
					this._DanhMucTinTuc.Entity = value;
					if ((value != null))
					{
						value.TinTucs.Add(this);
						this._IDDanhMucTinTuc = value.IDDanhMucTinTuc;
					}
					else
					{
						this._IDDanhMucTinTuc = default(Nullable<int>);
					}
					this.SendPropertyChanged("DanhMucTinTuc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThongBao")]
	public partial class ThongBao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDThongBao;
		
		private string _TieuDeThongBao;
		
		private string _NoiDungThongBao;
		
		private System.Nullable<System.DateTime> _NgayDangThongBao;
		
		private string _NguoiDangThongBao;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDThongBaoChanging(int value);
    partial void OnIDThongBaoChanged();
    partial void OnTieuDeThongBaoChanging(string value);
    partial void OnTieuDeThongBaoChanged();
    partial void OnNoiDungThongBaoChanging(string value);
    partial void OnNoiDungThongBaoChanged();
    partial void OnNgayDangThongBaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDangThongBaoChanged();
    partial void OnNguoiDangThongBaoChanging(string value);
    partial void OnNguoiDangThongBaoChanged();
    #endregion
		
		public ThongBao()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDThongBao", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDThongBao
		{
			get
			{
				return this._IDThongBao;
			}
			set
			{
				if ((this._IDThongBao != value))
				{
					this.OnIDThongBaoChanging(value);
					this.SendPropertyChanging();
					this._IDThongBao = value;
					this.SendPropertyChanged("IDThongBao");
					this.OnIDThongBaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDeThongBao", DbType="NVarChar(MAX)")]
		public string TieuDeThongBao
		{
			get
			{
				return this._TieuDeThongBao;
			}
			set
			{
				if ((this._TieuDeThongBao != value))
				{
					this.OnTieuDeThongBaoChanging(value);
					this.SendPropertyChanging();
					this._TieuDeThongBao = value;
					this.SendPropertyChanged("TieuDeThongBao");
					this.OnTieuDeThongBaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungThongBao", DbType="NVarChar(MAX)")]
		public string NoiDungThongBao
		{
			get
			{
				return this._NoiDungThongBao;
			}
			set
			{
				if ((this._NoiDungThongBao != value))
				{
					this.OnNoiDungThongBaoChanging(value);
					this.SendPropertyChanging();
					this._NoiDungThongBao = value;
					this.SendPropertyChanged("NoiDungThongBao");
					this.OnNoiDungThongBaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDangThongBao", DbType="Date")]
		public System.Nullable<System.DateTime> NgayDangThongBao
		{
			get
			{
				return this._NgayDangThongBao;
			}
			set
			{
				if ((this._NgayDangThongBao != value))
				{
					this.OnNgayDangThongBaoChanging(value);
					this.SendPropertyChanging();
					this._NgayDangThongBao = value;
					this.SendPropertyChanged("NgayDangThongBao");
					this.OnNgayDangThongBaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiDangThongBao", DbType="NVarChar(1)")]
		public string NguoiDangThongBao
		{
			get
			{
				return this._NguoiDangThongBao;
			}
			set
			{
				if ((this._NguoiDangThongBao != value))
				{
					this.OnNguoiDangThongBaoChanging(value);
					this.SendPropertyChanging();
					this._NguoiDangThongBao = value;
					this.SendPropertyChanged("NguoiDangThongBao");
					this.OnNguoiDangThongBaoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SuKien")]
	public partial class SuKien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDSuKien;
		
		private string _TenSuKien;
		
		private string _NoiDungSuKien;
		
		private System.Nullable<System.DateTime> _NgayDangSuKien;
		
		private string _NguoiDangSuKien;
		
		private System.Data.Linq.Binary _HinhAnhSuKien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDSuKienChanging(int value);
    partial void OnIDSuKienChanged();
    partial void OnTenSuKienChanging(string value);
    partial void OnTenSuKienChanged();
    partial void OnNoiDungSuKienChanging(string value);
    partial void OnNoiDungSuKienChanged();
    partial void OnNgayDangSuKienChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDangSuKienChanged();
    partial void OnNguoiDangSuKienChanging(string value);
    partial void OnNguoiDangSuKienChanged();
    partial void OnHinhAnhSuKienChanging(System.Data.Linq.Binary value);
    partial void OnHinhAnhSuKienChanged();
    #endregion
		
		public SuKien()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDSuKien", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDSuKien
		{
			get
			{
				return this._IDSuKien;
			}
			set
			{
				if ((this._IDSuKien != value))
				{
					this.OnIDSuKienChanging(value);
					this.SendPropertyChanging();
					this._IDSuKien = value;
					this.SendPropertyChanged("IDSuKien");
					this.OnIDSuKienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSuKien", DbType="NVarChar(200)")]
		public string TenSuKien
		{
			get
			{
				return this._TenSuKien;
			}
			set
			{
				if ((this._TenSuKien != value))
				{
					this.OnTenSuKienChanging(value);
					this.SendPropertyChanging();
					this._TenSuKien = value;
					this.SendPropertyChanged("TenSuKien");
					this.OnTenSuKienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungSuKien", DbType="NVarChar(MAX)")]
		public string NoiDungSuKien
		{
			get
			{
				return this._NoiDungSuKien;
			}
			set
			{
				if ((this._NoiDungSuKien != value))
				{
					this.OnNoiDungSuKienChanging(value);
					this.SendPropertyChanging();
					this._NoiDungSuKien = value;
					this.SendPropertyChanged("NoiDungSuKien");
					this.OnNoiDungSuKienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDangSuKien", DbType="Date")]
		public System.Nullable<System.DateTime> NgayDangSuKien
		{
			get
			{
				return this._NgayDangSuKien;
			}
			set
			{
				if ((this._NgayDangSuKien != value))
				{
					this.OnNgayDangSuKienChanging(value);
					this.SendPropertyChanging();
					this._NgayDangSuKien = value;
					this.SendPropertyChanged("NgayDangSuKien");
					this.OnNgayDangSuKienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiDangSuKien", DbType="NVarChar(50)")]
		public string NguoiDangSuKien
		{
			get
			{
				return this._NguoiDangSuKien;
			}
			set
			{
				if ((this._NguoiDangSuKien != value))
				{
					this.OnNguoiDangSuKienChanging(value);
					this.SendPropertyChanging();
					this._NguoiDangSuKien = value;
					this.SendPropertyChanged("NguoiDangSuKien");
					this.OnNguoiDangSuKienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnhSuKien", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary HinhAnhSuKien
		{
			get
			{
				return this._HinhAnhSuKien;
			}
			set
			{
				if ((this._HinhAnhSuKien != value))
				{
					this.OnHinhAnhSuKienChanging(value);
					this.SendPropertyChanging();
					this._HinhAnhSuKien = value;
					this.SendPropertyChanged("HinhAnhSuKien");
					this.OnHinhAnhSuKienChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhomHocPhan")]
	public partial class NhomHocPhan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNhom;
		
		private string _TenNhom;
		
		private string _TenLop;
		
		private EntitySet<CongTacGiangDay> _CongTacGiangDays;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhomChanging(int value);
    partial void OnMaNhomChanged();
    partial void OnTenNhomChanging(string value);
    partial void OnTenNhomChanged();
    partial void OnTenLopChanging(string value);
    partial void OnTenLopChanged();
    #endregion
		
		public NhomHocPhan()
		{
			this._CongTacGiangDays = new EntitySet<CongTacGiangDay>(new Action<CongTacGiangDay>(this.attach_CongTacGiangDays), new Action<CongTacGiangDay>(this.detach_CongTacGiangDays));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhom", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaNhom
		{
			get
			{
				return this._MaNhom;
			}
			set
			{
				if ((this._MaNhom != value))
				{
					this.OnMaNhomChanging(value);
					this.SendPropertyChanging();
					this._MaNhom = value;
					this.SendPropertyChanged("MaNhom");
					this.OnMaNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhom", DbType="NVarChar(50)")]
		public string TenNhom
		{
			get
			{
				return this._TenNhom;
			}
			set
			{
				if ((this._TenNhom != value))
				{
					this.OnTenNhomChanging(value);
					this.SendPropertyChanging();
					this._TenNhom = value;
					this.SendPropertyChanged("TenNhom");
					this.OnTenNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLop", DbType="NVarChar(50)")]
		public string TenLop
		{
			get
			{
				return this._TenLop;
			}
			set
			{
				if ((this._TenLop != value))
				{
					this.OnTenLopChanging(value);
					this.SendPropertyChanging();
					this._TenLop = value;
					this.SendPropertyChanged("TenLop");
					this.OnTenLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomHocPhan_CongTacGiangDay", Storage="_CongTacGiangDays", ThisKey="MaNhom", OtherKey="MaNhom")]
		public EntitySet<CongTacGiangDay> CongTacGiangDays
		{
			get
			{
				return this._CongTacGiangDays;
			}
			set
			{
				this._CongTacGiangDays.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CongTacGiangDays(CongTacGiangDay entity)
		{
			this.SendPropertyChanging();
			entity.NhomHocPhan = this;
		}
		
		private void detach_CongTacGiangDays(CongTacGiangDay entity)
		{
			this.SendPropertyChanging();
			entity.NhomHocPhan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NguoiDung")]
	public partial class NguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDNguoiDung;
		
		private string _TenDangNhap;
		
		private string _MatKhau;
		
		private string _HoTen;
		
		private string _DiaChi;
		
		private string _SoDienThoai;
		
		private string _Email;
		
		private System.Nullable<int> _IDKieuNguoiDung;
		
		private EntityRef<KieuNguoiDung> _KieuNguoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDNguoiDungChanging(int value);
    partial void OnIDNguoiDungChanged();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnIDKieuNguoiDungChanging(System.Nullable<int> value);
    partial void OnIDKieuNguoiDungChanged();
    #endregion
		
		public NguoiDung()
		{
			this._KieuNguoiDung = default(EntityRef<KieuNguoiDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNguoiDung", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDNguoiDung
		{
			get
			{
				return this._IDNguoiDung;
			}
			set
			{
				if ((this._IDNguoiDung != value))
				{
					this.OnIDNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._IDNguoiDung = value;
					this.SendPropertyChanged("IDNguoiDung");
					this.OnIDNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="NVarChar(50)")]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(50)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(300)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="VarChar(10)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDKieuNguoiDung", DbType="Int")]
		public System.Nullable<int> IDKieuNguoiDung
		{
			get
			{
				return this._IDKieuNguoiDung;
			}
			set
			{
				if ((this._IDKieuNguoiDung != value))
				{
					if (this._KieuNguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDKieuNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._IDKieuNguoiDung = value;
					this.SendPropertyChanged("IDKieuNguoiDung");
					this.OnIDKieuNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KieuNguoiDung_NguoiDung", Storage="_KieuNguoiDung", ThisKey="IDKieuNguoiDung", OtherKey="IDKieuNguoiDung", IsForeignKey=true)]
		public KieuNguoiDung KieuNguoiDung
		{
			get
			{
				return this._KieuNguoiDung.Entity;
			}
			set
			{
				KieuNguoiDung previousValue = this._KieuNguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._KieuNguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KieuNguoiDung.Entity = null;
						previousValue.NguoiDungs.Remove(this);
					}
					this._KieuNguoiDung.Entity = value;
					if ((value != null))
					{
						value.NguoiDungs.Add(this);
						this._IDKieuNguoiDung = value.IDKieuNguoiDung;
					}
					else
					{
						this._IDKieuNguoiDung = default(Nullable<int>);
					}
					this.SendPropertyChanged("KieuNguoiDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NamHoc")]
	public partial class NamHoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDNamHoc;
		
		private string _TenHocKy;
		
		private string _NamHoc1;
		
		private EntitySet<CongTacGiangDay> _CongTacGiangDays;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDNamHocChanging(int value);
    partial void OnIDNamHocChanged();
    partial void OnTenHocKyChanging(string value);
    partial void OnTenHocKyChanged();
    partial void OnNamHoc1Changing(string value);
    partial void OnNamHoc1Changed();
    #endregion
		
		public NamHoc()
		{
			this._CongTacGiangDays = new EntitySet<CongTacGiangDay>(new Action<CongTacGiangDay>(this.attach_CongTacGiangDays), new Action<CongTacGiangDay>(this.detach_CongTacGiangDays));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNamHoc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDNamHoc
		{
			get
			{
				return this._IDNamHoc;
			}
			set
			{
				if ((this._IDNamHoc != value))
				{
					this.OnIDNamHocChanging(value);
					this.SendPropertyChanging();
					this._IDNamHoc = value;
					this.SendPropertyChanged("IDNamHoc");
					this.OnIDNamHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHocKy", DbType="NVarChar(50)")]
		public string TenHocKy
		{
			get
			{
				return this._TenHocKy;
			}
			set
			{
				if ((this._TenHocKy != value))
				{
					this.OnTenHocKyChanging(value);
					this.SendPropertyChanging();
					this._TenHocKy = value;
					this.SendPropertyChanged("TenHocKy");
					this.OnTenHocKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="NamHoc", Storage="_NamHoc1", DbType="NVarChar(50)")]
		public string NamHoc1
		{
			get
			{
				return this._NamHoc1;
			}
			set
			{
				if ((this._NamHoc1 != value))
				{
					this.OnNamHoc1Changing(value);
					this.SendPropertyChanging();
					this._NamHoc1 = value;
					this.SendPropertyChanged("NamHoc1");
					this.OnNamHoc1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NamHoc_CongTacGiangDay", Storage="_CongTacGiangDays", ThisKey="IDNamHoc", OtherKey="IDNamHoc")]
		public EntitySet<CongTacGiangDay> CongTacGiangDays
		{
			get
			{
				return this._CongTacGiangDays;
			}
			set
			{
				this._CongTacGiangDays.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CongTacGiangDays(CongTacGiangDay entity)
		{
			this.SendPropertyChanging();
			entity.NamHoc = this;
		}
		
		private void detach_CongTacGiangDays(CongTacGiangDay entity)
		{
			this.SendPropertyChanging();
			entity.NamHoc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LienHe")]
	public partial class LienHe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDLienHe;
		
		private string _HoTen;
		
		private string _DiaChi;
		
		private string _SoDienThoai;
		
		private string _Email;
		
		private string _NoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDLienHeChanging(int value);
    partial void OnIDLienHeChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    #endregion
		
		public LienHe()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDLienHe", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDLienHe
		{
			get
			{
				return this._IDLienHe;
			}
			set
			{
				if ((this._IDLienHe != value))
				{
					this.OnIDLienHeChanging(value);
					this.SendPropertyChanging();
					this._IDLienHe = value;
					this.SendPropertyChanged("IDLienHe");
					this.OnIDLienHeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="VarChar(10)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(MAX)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KieuNguoiDung")]
	public partial class KieuNguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDKieuNguoiDung;
		
		private string _TenKieuNguoiDung;
		
		private EntitySet<NguoiDung> _NguoiDungs;
		
		private EntitySet<GiangVien> _GiangViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDKieuNguoiDungChanging(int value);
    partial void OnIDKieuNguoiDungChanged();
    partial void OnTenKieuNguoiDungChanging(string value);
    partial void OnTenKieuNguoiDungChanged();
    #endregion
		
		public KieuNguoiDung()
		{
			this._NguoiDungs = new EntitySet<NguoiDung>(new Action<NguoiDung>(this.attach_NguoiDungs), new Action<NguoiDung>(this.detach_NguoiDungs));
			this._GiangViens = new EntitySet<GiangVien>(new Action<GiangVien>(this.attach_GiangViens), new Action<GiangVien>(this.detach_GiangViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDKieuNguoiDung", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDKieuNguoiDung
		{
			get
			{
				return this._IDKieuNguoiDung;
			}
			set
			{
				if ((this._IDKieuNguoiDung != value))
				{
					this.OnIDKieuNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._IDKieuNguoiDung = value;
					this.SendPropertyChanged("IDKieuNguoiDung");
					this.OnIDKieuNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKieuNguoiDung", DbType="NVarChar(50)")]
		public string TenKieuNguoiDung
		{
			get
			{
				return this._TenKieuNguoiDung;
			}
			set
			{
				if ((this._TenKieuNguoiDung != value))
				{
					this.OnTenKieuNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._TenKieuNguoiDung = value;
					this.SendPropertyChanged("TenKieuNguoiDung");
					this.OnTenKieuNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KieuNguoiDung_NguoiDung", Storage="_NguoiDungs", ThisKey="IDKieuNguoiDung", OtherKey="IDKieuNguoiDung")]
		public EntitySet<NguoiDung> NguoiDungs
		{
			get
			{
				return this._NguoiDungs;
			}
			set
			{
				this._NguoiDungs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KieuNguoiDung_GiangVien", Storage="_GiangViens", ThisKey="IDKieuNguoiDung", OtherKey="IDKieuNguoiDung")]
		public EntitySet<GiangVien> GiangViens
		{
			get
			{
				return this._GiangViens;
			}
			set
			{
				this._GiangViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NguoiDungs(NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.KieuNguoiDung = this;
		}
		
		private void detach_NguoiDungs(NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.KieuNguoiDung = null;
		}
		
		private void attach_GiangViens(GiangVien entity)
		{
			this.SendPropertyChanging();
			entity.KieuNguoiDung = this;
		}
		
		private void detach_GiangViens(GiangVien entity)
		{
			this.SendPropertyChanging();
			entity.KieuNguoiDung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HocPhan")]
	public partial class HocPhan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHocPhan;
		
		private string _TenHocPhan;
		
		private System.Nullable<int> _SoTiet;
		
		private System.Nullable<int> _LyThuyet;
		
		private System.Nullable<int> _ThucHanh;
		
		private System.Nullable<int> _SoTinChi;
		
		private EntitySet<CongTacGiangDay> _CongTacGiangDays;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHocPhanChanging(string value);
    partial void OnMaHocPhanChanged();
    partial void OnTenHocPhanChanging(string value);
    partial void OnTenHocPhanChanged();
    partial void OnSoTietChanging(System.Nullable<int> value);
    partial void OnSoTietChanged();
    partial void OnLyThuyetChanging(System.Nullable<int> value);
    partial void OnLyThuyetChanged();
    partial void OnThucHanhChanging(System.Nullable<int> value);
    partial void OnThucHanhChanged();
    partial void OnSoTinChiChanging(System.Nullable<int> value);
    partial void OnSoTinChiChanged();
    #endregion
		
		public HocPhan()
		{
			this._CongTacGiangDays = new EntitySet<CongTacGiangDay>(new Action<CongTacGiangDay>(this.attach_CongTacGiangDays), new Action<CongTacGiangDay>(this.detach_CongTacGiangDays));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHocPhan", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHocPhan
		{
			get
			{
				return this._MaHocPhan;
			}
			set
			{
				if ((this._MaHocPhan != value))
				{
					this.OnMaHocPhanChanging(value);
					this.SendPropertyChanging();
					this._MaHocPhan = value;
					this.SendPropertyChanged("MaHocPhan");
					this.OnMaHocPhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHocPhan", DbType="NVarChar(50)")]
		public string TenHocPhan
		{
			get
			{
				return this._TenHocPhan;
			}
			set
			{
				if ((this._TenHocPhan != value))
				{
					this.OnTenHocPhanChanging(value);
					this.SendPropertyChanging();
					this._TenHocPhan = value;
					this.SendPropertyChanged("TenHocPhan");
					this.OnTenHocPhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTiet", DbType="Int")]
		public System.Nullable<int> SoTiet
		{
			get
			{
				return this._SoTiet;
			}
			set
			{
				if ((this._SoTiet != value))
				{
					this.OnSoTietChanging(value);
					this.SendPropertyChanging();
					this._SoTiet = value;
					this.SendPropertyChanged("SoTiet");
					this.OnSoTietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LyThuyet", DbType="Int")]
		public System.Nullable<int> LyThuyet
		{
			get
			{
				return this._LyThuyet;
			}
			set
			{
				if ((this._LyThuyet != value))
				{
					this.OnLyThuyetChanging(value);
					this.SendPropertyChanging();
					this._LyThuyet = value;
					this.SendPropertyChanged("LyThuyet");
					this.OnLyThuyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThucHanh", DbType="Int")]
		public System.Nullable<int> ThucHanh
		{
			get
			{
				return this._ThucHanh;
			}
			set
			{
				if ((this._ThucHanh != value))
				{
					this.OnThucHanhChanging(value);
					this.SendPropertyChanging();
					this._ThucHanh = value;
					this.SendPropertyChanged("ThucHanh");
					this.OnThucHanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTinChi", DbType="Int")]
		public System.Nullable<int> SoTinChi
		{
			get
			{
				return this._SoTinChi;
			}
			set
			{
				if ((this._SoTinChi != value))
				{
					this.OnSoTinChiChanging(value);
					this.SendPropertyChanging();
					this._SoTinChi = value;
					this.SendPropertyChanged("SoTinChi");
					this.OnSoTinChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HocPhan_CongTacGiangDay", Storage="_CongTacGiangDays", ThisKey="MaHocPhan", OtherKey="MaHocPhan")]
		public EntitySet<CongTacGiangDay> CongTacGiangDays
		{
			get
			{
				return this._CongTacGiangDays;
			}
			set
			{
				this._CongTacGiangDays.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CongTacGiangDays(CongTacGiangDay entity)
		{
			this.SendPropertyChanging();
			entity.HocPhan = this;
		}
		
		private void detach_CongTacGiangDays(CongTacGiangDay entity)
		{
			this.SendPropertyChanging();
			entity.HocPhan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GiangVien")]
	public partial class GiangVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaGV;
		
		private string _TenGiangVien;
		
		private string _NgaySinh;
		
		private System.Nullable<int> _IDBoMon;
		
		private string _DiaChi;
		
		private string _SoDienThoai;
		
		private string _Email;
		
		private System.Data.Linq.Binary _HinhAnh;
		
		private string _HocVi;
		
		private string _TenDangNhap;
		
		private string _MatKhau;
		
		private System.Nullable<int> _IDKieuNguoiDung;
		
		private string _ChucVu;
		
		private EntitySet<CongTacGiangDay> _CongTacGiangDays;
		
		private EntityRef<KieuNguoiDung> _KieuNguoiDung;
		
		private EntityRef<BoMon> _BoMon;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGVChanging(int value);
    partial void OnMaGVChanged();
    partial void OnTenGiangVienChanging(string value);
    partial void OnTenGiangVienChanged();
    partial void OnNgaySinhChanging(string value);
    partial void OnNgaySinhChanged();
    partial void OnIDBoMonChanging(System.Nullable<int> value);
    partial void OnIDBoMonChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnHinhAnhChanging(System.Data.Linq.Binary value);
    partial void OnHinhAnhChanged();
    partial void OnHocViChanging(string value);
    partial void OnHocViChanged();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnIDKieuNguoiDungChanging(System.Nullable<int> value);
    partial void OnIDKieuNguoiDungChanged();
    partial void OnChucVuChanging(string value);
    partial void OnChucVuChanged();
    #endregion
		
		public GiangVien()
		{
			this._CongTacGiangDays = new EntitySet<CongTacGiangDay>(new Action<CongTacGiangDay>(this.attach_CongTacGiangDays), new Action<CongTacGiangDay>(this.detach_CongTacGiangDays));
			this._KieuNguoiDung = default(EntityRef<KieuNguoiDung>);
			this._BoMon = default(EntityRef<BoMon>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaGV
		{
			get
			{
				return this._MaGV;
			}
			set
			{
				if ((this._MaGV != value))
				{
					this.OnMaGVChanging(value);
					this.SendPropertyChanging();
					this._MaGV = value;
					this.SendPropertyChanged("MaGV");
					this.OnMaGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenGiangVien", DbType="NVarChar(50)")]
		public string TenGiangVien
		{
			get
			{
				return this._TenGiangVien;
			}
			set
			{
				if ((this._TenGiangVien != value))
				{
					this.OnTenGiangVienChanging(value);
					this.SendPropertyChanging();
					this._TenGiangVien = value;
					this.SendPropertyChanged("TenGiangVien");
					this.OnTenGiangVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="VarChar(50)")]
		public string NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDBoMon", DbType="Int")]
		public System.Nullable<int> IDBoMon
		{
			get
			{
				return this._IDBoMon;
			}
			set
			{
				if ((this._IDBoMon != value))
				{
					if (this._BoMon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDBoMonChanging(value);
					this.SendPropertyChanging();
					this._IDBoMon = value;
					this.SendPropertyChanged("IDBoMon");
					this.OnIDBoMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(300)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="VarChar(10)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HocVi", DbType="NVarChar(50)")]
		public string HocVi
		{
			get
			{
				return this._HocVi;
			}
			set
			{
				if ((this._HocVi != value))
				{
					this.OnHocViChanging(value);
					this.SendPropertyChanging();
					this._HocVi = value;
					this.SendPropertyChanged("HocVi");
					this.OnHocViChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="NVarChar(50)")]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(50)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDKieuNguoiDung", DbType="Int")]
		public System.Nullable<int> IDKieuNguoiDung
		{
			get
			{
				return this._IDKieuNguoiDung;
			}
			set
			{
				if ((this._IDKieuNguoiDung != value))
				{
					if (this._KieuNguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDKieuNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._IDKieuNguoiDung = value;
					this.SendPropertyChanged("IDKieuNguoiDung");
					this.OnIDKieuNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVu", DbType="NVarChar(50)")]
		public string ChucVu
		{
			get
			{
				return this._ChucVu;
			}
			set
			{
				if ((this._ChucVu != value))
				{
					this.OnChucVuChanging(value);
					this.SendPropertyChanging();
					this._ChucVu = value;
					this.SendPropertyChanged("ChucVu");
					this.OnChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiangVien_CongTacGiangDay", Storage="_CongTacGiangDays", ThisKey="MaGV", OtherKey="MaGV")]
		public EntitySet<CongTacGiangDay> CongTacGiangDays
		{
			get
			{
				return this._CongTacGiangDays;
			}
			set
			{
				this._CongTacGiangDays.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KieuNguoiDung_GiangVien", Storage="_KieuNguoiDung", ThisKey="IDKieuNguoiDung", OtherKey="IDKieuNguoiDung", IsForeignKey=true)]
		public KieuNguoiDung KieuNguoiDung
		{
			get
			{
				return this._KieuNguoiDung.Entity;
			}
			set
			{
				KieuNguoiDung previousValue = this._KieuNguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._KieuNguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KieuNguoiDung.Entity = null;
						previousValue.GiangViens.Remove(this);
					}
					this._KieuNguoiDung.Entity = value;
					if ((value != null))
					{
						value.GiangViens.Add(this);
						this._IDKieuNguoiDung = value.IDKieuNguoiDung;
					}
					else
					{
						this._IDKieuNguoiDung = default(Nullable<int>);
					}
					this.SendPropertyChanged("KieuNguoiDung");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BoMon_GiangVien", Storage="_BoMon", ThisKey="IDBoMon", OtherKey="IDBoMon", IsForeignKey=true)]
		public BoMon BoMon
		{
			get
			{
				return this._BoMon.Entity;
			}
			set
			{
				BoMon previousValue = this._BoMon.Entity;
				if (((previousValue != value) 
							|| (this._BoMon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BoMon.Entity = null;
						previousValue.GiangViens.Remove(this);
					}
					this._BoMon.Entity = value;
					if ((value != null))
					{
						value.GiangViens.Add(this);
						this._IDBoMon = value.IDBoMon;
					}
					else
					{
						this._IDBoMon = default(Nullable<int>);
					}
					this.SendPropertyChanged("BoMon");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CongTacGiangDays(CongTacGiangDay entity)
		{
			this.SendPropertyChanging();
			entity.GiangVien = this;
		}
		
		private void detach_CongTacGiangDays(CongTacGiangDay entity)
		{
			this.SendPropertyChanging();
			entity.GiangVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DangNhap")]
	public partial class DangNhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenDangNhap;
		
		private string _MatKhau;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    #endregion
		
		public DangNhap()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(50)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DanhMucTinTuc")]
	public partial class DanhMucTinTuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDDanhMucTinTuc;
		
		private System.Nullable<int> _TenDanhMucTinTuc;
		
		private EntitySet<TinTuc> _TinTucs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDDanhMucTinTucChanging(int value);
    partial void OnIDDanhMucTinTucChanged();
    partial void OnTenDanhMucTinTucChanging(System.Nullable<int> value);
    partial void OnTenDanhMucTinTucChanged();
    #endregion
		
		public DanhMucTinTuc()
		{
			this._TinTucs = new EntitySet<TinTuc>(new Action<TinTuc>(this.attach_TinTucs), new Action<TinTuc>(this.detach_TinTucs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDanhMucTinTuc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDDanhMucTinTuc
		{
			get
			{
				return this._IDDanhMucTinTuc;
			}
			set
			{
				if ((this._IDDanhMucTinTuc != value))
				{
					this.OnIDDanhMucTinTucChanging(value);
					this.SendPropertyChanging();
					this._IDDanhMucTinTuc = value;
					this.SendPropertyChanged("IDDanhMucTinTuc");
					this.OnIDDanhMucTinTucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDanhMucTinTuc", DbType="Int")]
		public System.Nullable<int> TenDanhMucTinTuc
		{
			get
			{
				return this._TenDanhMucTinTuc;
			}
			set
			{
				if ((this._TenDanhMucTinTuc != value))
				{
					this.OnTenDanhMucTinTucChanging(value);
					this.SendPropertyChanging();
					this._TenDanhMucTinTuc = value;
					this.SendPropertyChanged("TenDanhMucTinTuc");
					this.OnTenDanhMucTinTucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DanhMucTinTuc_TinTuc", Storage="_TinTucs", ThisKey="IDDanhMucTinTuc", OtherKey="IDDanhMucTinTuc")]
		public EntitySet<TinTuc> TinTucs
		{
			get
			{
				return this._TinTucs;
			}
			set
			{
				this._TinTucs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TinTucs(TinTuc entity)
		{
			this.SendPropertyChanging();
			entity.DanhMucTinTuc = this;
		}
		
		private void detach_TinTucs(TinTuc entity)
		{
			this.SendPropertyChanging();
			entity.DanhMucTinTuc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CongTacGiangDay")]
	public partial class CongTacGiangDay : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaGV;
		
		private int _IDNamHoc;
		
		private string _MaHocPhan;
		
		private int _MaNhom;
		
		private System.Nullable<decimal> _HeSo;
		
		private EntityRef<NamHoc> _NamHoc;
		
		private EntityRef<HocPhan> _HocPhan;
		
		private EntityRef<NhomHocPhan> _NhomHocPhan;
		
		private EntityRef<GiangVien> _GiangVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGVChanging(int value);
    partial void OnMaGVChanged();
    partial void OnIDNamHocChanging(int value);
    partial void OnIDNamHocChanged();
    partial void OnMaHocPhanChanging(string value);
    partial void OnMaHocPhanChanged();
    partial void OnMaNhomChanging(int value);
    partial void OnMaNhomChanged();
    partial void OnHeSoChanging(System.Nullable<decimal> value);
    partial void OnHeSoChanged();
    #endregion
		
		public CongTacGiangDay()
		{
			this._NamHoc = default(EntityRef<NamHoc>);
			this._HocPhan = default(EntityRef<HocPhan>);
			this._NhomHocPhan = default(EntityRef<NhomHocPhan>);
			this._GiangVien = default(EntityRef<GiangVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGV", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaGV
		{
			get
			{
				return this._MaGV;
			}
			set
			{
				if ((this._MaGV != value))
				{
					if (this._GiangVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaGVChanging(value);
					this.SendPropertyChanging();
					this._MaGV = value;
					this.SendPropertyChanged("MaGV");
					this.OnMaGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNamHoc", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDNamHoc
		{
			get
			{
				return this._IDNamHoc;
			}
			set
			{
				if ((this._IDNamHoc != value))
				{
					if (this._NamHoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDNamHocChanging(value);
					this.SendPropertyChanging();
					this._IDNamHoc = value;
					this.SendPropertyChanged("IDNamHoc");
					this.OnIDNamHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHocPhan", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHocPhan
		{
			get
			{
				return this._MaHocPhan;
			}
			set
			{
				if ((this._MaHocPhan != value))
				{
					if (this._HocPhan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHocPhanChanging(value);
					this.SendPropertyChanging();
					this._MaHocPhan = value;
					this.SendPropertyChanged("MaHocPhan");
					this.OnMaHocPhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhom", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaNhom
		{
			get
			{
				return this._MaNhom;
			}
			set
			{
				if ((this._MaNhom != value))
				{
					if (this._NhomHocPhan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhomChanging(value);
					this.SendPropertyChanging();
					this._MaNhom = value;
					this.SendPropertyChanged("MaNhom");
					this.OnMaNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeSo", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> HeSo
		{
			get
			{
				return this._HeSo;
			}
			set
			{
				if ((this._HeSo != value))
				{
					this.OnHeSoChanging(value);
					this.SendPropertyChanging();
					this._HeSo = value;
					this.SendPropertyChanged("HeSo");
					this.OnHeSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NamHoc_CongTacGiangDay", Storage="_NamHoc", ThisKey="IDNamHoc", OtherKey="IDNamHoc", IsForeignKey=true)]
		public NamHoc NamHoc
		{
			get
			{
				return this._NamHoc.Entity;
			}
			set
			{
				NamHoc previousValue = this._NamHoc.Entity;
				if (((previousValue != value) 
							|| (this._NamHoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NamHoc.Entity = null;
						previousValue.CongTacGiangDays.Remove(this);
					}
					this._NamHoc.Entity = value;
					if ((value != null))
					{
						value.CongTacGiangDays.Add(this);
						this._IDNamHoc = value.IDNamHoc;
					}
					else
					{
						this._IDNamHoc = default(int);
					}
					this.SendPropertyChanged("NamHoc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HocPhan_CongTacGiangDay", Storage="_HocPhan", ThisKey="MaHocPhan", OtherKey="MaHocPhan", IsForeignKey=true)]
		public HocPhan HocPhan
		{
			get
			{
				return this._HocPhan.Entity;
			}
			set
			{
				HocPhan previousValue = this._HocPhan.Entity;
				if (((previousValue != value) 
							|| (this._HocPhan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HocPhan.Entity = null;
						previousValue.CongTacGiangDays.Remove(this);
					}
					this._HocPhan.Entity = value;
					if ((value != null))
					{
						value.CongTacGiangDays.Add(this);
						this._MaHocPhan = value.MaHocPhan;
					}
					else
					{
						this._MaHocPhan = default(string);
					}
					this.SendPropertyChanged("HocPhan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomHocPhan_CongTacGiangDay", Storage="_NhomHocPhan", ThisKey="MaNhom", OtherKey="MaNhom", IsForeignKey=true)]
		public NhomHocPhan NhomHocPhan
		{
			get
			{
				return this._NhomHocPhan.Entity;
			}
			set
			{
				NhomHocPhan previousValue = this._NhomHocPhan.Entity;
				if (((previousValue != value) 
							|| (this._NhomHocPhan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhomHocPhan.Entity = null;
						previousValue.CongTacGiangDays.Remove(this);
					}
					this._NhomHocPhan.Entity = value;
					if ((value != null))
					{
						value.CongTacGiangDays.Add(this);
						this._MaNhom = value.MaNhom;
					}
					else
					{
						this._MaNhom = default(int);
					}
					this.SendPropertyChanged("NhomHocPhan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiangVien_CongTacGiangDay", Storage="_GiangVien", ThisKey="MaGV", OtherKey="MaGV", IsForeignKey=true)]
		public GiangVien GiangVien
		{
			get
			{
				return this._GiangVien.Entity;
			}
			set
			{
				GiangVien previousValue = this._GiangVien.Entity;
				if (((previousValue != value) 
							|| (this._GiangVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GiangVien.Entity = null;
						previousValue.CongTacGiangDays.Remove(this);
					}
					this._GiangVien.Entity = value;
					if ((value != null))
					{
						value.CongTacGiangDays.Add(this);
						this._MaGV = value.MaGV;
					}
					else
					{
						this._MaGV = default(int);
					}
					this.SendPropertyChanged("GiangVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BoMon")]
	public partial class BoMon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDBoMon;
		
		private string _TenBoMon;
		
		private EntitySet<GiangVien> _GiangViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDBoMonChanging(int value);
    partial void OnIDBoMonChanged();
    partial void OnTenBoMonChanging(string value);
    partial void OnTenBoMonChanged();
    #endregion
		
		public BoMon()
		{
			this._GiangViens = new EntitySet<GiangVien>(new Action<GiangVien>(this.attach_GiangViens), new Action<GiangVien>(this.detach_GiangViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDBoMon", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDBoMon
		{
			get
			{
				return this._IDBoMon;
			}
			set
			{
				if ((this._IDBoMon != value))
				{
					this.OnIDBoMonChanging(value);
					this.SendPropertyChanging();
					this._IDBoMon = value;
					this.SendPropertyChanged("IDBoMon");
					this.OnIDBoMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenBoMon", DbType="NVarChar(50)")]
		public string TenBoMon
		{
			get
			{
				return this._TenBoMon;
			}
			set
			{
				if ((this._TenBoMon != value))
				{
					this.OnTenBoMonChanging(value);
					this.SendPropertyChanging();
					this._TenBoMon = value;
					this.SendPropertyChanged("TenBoMon");
					this.OnTenBoMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BoMon_GiangVien", Storage="_GiangViens", ThisKey="IDBoMon", OtherKey="IDBoMon")]
		public EntitySet<GiangVien> GiangViens
		{
			get
			{
				return this._GiangViens;
			}
			set
			{
				this._GiangViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GiangViens(GiangVien entity)
		{
			this.SendPropertyChanging();
			entity.BoMon = this;
		}
		
		private void detach_GiangViens(GiangVien entity)
		{
			this.SendPropertyChanging();
			entity.BoMon = null;
		}
	}
}
#pragma warning restore 1591
